In [84]:
import pandas as pd

In [85]:
df_filmes_brasileiros = pd.read_csv(r'..\datasets\filmes_brasileiros.csv')
df_filmes_brasileiros.head()
pd.set_option('display.max_rows', None)

C:\Users\dev-gus\AppData\Local\Temp\ipykernel_11812\1357551787.py:1: DtypeWarning: Columns (0: startYear) have mixed types. Specify dtype option on import or set low_memory=False.
  df_filmes_brasileiros = pd.read_csv(r'..\datasets\filmes_brasileiros.csv')

In [86]:
list(df_filmes_brasileiros.columns)

['index',
 'titleId',
 'ordering',
 'title',
 'region',
 'language',
 'types',
 'attributes',
 'isOriginalTitle',
 'tconst_x',
 'titleType',
 'primaryTitle',
 'originalTitle',
 'isAdult',
 'startYear',
 'endYear',
 'runtimeMinutes',
 'genres',
 'tconst_y',
 'averageRating',
 'numVotes']

In [87]:
df_filmes_brasileiros = df_filmes_brasileiros[[
 'titleId',
 'ordering',
 'title',
 'region',
 'language',
 'types',
 'attributes',
 'isOriginalTitle',
 'titleType',
 'primaryTitle',
 'originalTitle',
 'isAdult',
 'startYear',
 'endYear',
 'runtimeMinutes',
 'genres',
 'averageRating',
 'numVotes']]

In [88]:
df_filmes_brasileiros.describe()

,ordering,isOriginalTitle,isAdult,averageRating,numVotes
count,78896.000000,78896.0,78896.000000,71400.000000,7.140000e+04
mean,12.368409,0.0,0.005856,6.066237,1.831089e+04
std,10.510056,0.0,0.076299,1.108002,8.616645e+04
min,2.000000,0.0,0.000000,1.000000,5.000000e+00
25%,4.000000,0.0,0.000000,5.400000,1.980000e+02
50%,9.000000,0.0,0.000000,6.200000,9.760000e+02
75%,18.000000,0.0,0.000000,6.800000,5.160000e+03
max,170.000000,0.0,1.000000,10.000000,3.175959e+06

In [89]:
df_filmes_brasileiros.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000838,3,Cultura do Cacau em S. Tome,BR,\N,alternative,\N,0,movie,A Cultura do Cacau,A Cultura do Cacau,0,1909,\N,\N,\N,2.8,18.0
1,tt0002130,10,Inferno,BR,\N,imdbDisplay,\N,0,movie,Dante's Inferno,L'inferno,0,1911,\N,71,"Adventure,Drama,Fantasy",7.1,4094.0
2,tt0002199,2,Da Manjedoura à Cruz,BR,\N,imdbDisplay,\N,0,movie,From the Manger to the Cross,From the Manger to the Cross,0,1912,\N,71,"Biography,Drama",5.9,708.0
3,tt0002423,2,Madame DuBarry,BR,\N,imdbDisplay,\N,0,movie,Passion,Madame DuBarry,0,1919,\N,113,"Biography,Drama,Romance",6.7,1126.0
4,tt0003131,6,Maldita seja a guerra!,BR,\N,imdbDisplay,\N,0,movie,War Is Hell,Maudite soit la guerre,0,1914,\N,50,"Drama,War",6.6,212.0

In [90]:
#Analisando variável startYear, percebemos que existem valores nulos representados por '\N', o que impede a conversão direta para inteiro. Para resolver isso, podemos substituir esses valores por 0 ou outro valor que faça sentido para a análise, e então converter a coluna para inteiro.

df_filmes_brasileiros['startYear'] = df_filmes_brasileiros['startYear'].apply(lambda x: 0 if (x == '\\N' or x == '\\N') else int(x))

df_filmes_brasileiros[df_filmes_brasileiros.startYear == '\\N']

Empty DataFrame
Columns: [titleId, ordering, title, region, language, types, attributes, isOriginalTitle, titleType, primaryTitle, originalTitle, isAdult, startYear, endYear, runtimeMinutes, genres, averageRating, numVotes]
Index: []

In [91]:
df_filmes_brasileiros['startYear'] = df_filmes_brasileiros['startYear'].astype(int)

In [106]:
df_filmes_brasileiros.startYear.max()

print('Identificado possiveis filmes com data de lançamento.')

Identificado possiveis filmes com data de lançamento.

In [112]:
#verificando filmes com lançamentos futuros

filmes_futuros = df_filmes_brasileiros[df_filmes_brasileiros['startYear'] > 2026]

print('Há {} filmes com data de lançamento futura.'.format(filmes_futuros.shape[0]))

Há 21 filmes com data de lançamento futura.

In [118]:
filmes_futuros.sample(3)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
67828,tt33323550,2,The Mouse Trap: Bem-vindos ao Mickeyverso,BR,\N,imdbDisplay,\N,0,movie,The Mouse Trap: Welcome to the Mickeyverse,The Mouse Trap: Welcome to The Mickeyverse,0,2027,\N,80,Horror,NaN,NaN
58353,tt16360004,22,Homem-Aranha: Além do Aranhaverso,BR,\N,imdbDisplay,\N,0,movie,Spider-Man: Beyond the Spider-Verse,Spider-Man: Beyond the Spider-Verse,0,2027,\N,\N,"Action,Adventure,Animation",NaN,NaN
61580,tt21361444,13,Vingadores: Guerras Secretas,BR,\N,imdbDisplay,\N,0,movie,Avengers: Secret Wars,Avengers: Secret Wars,0,2027,\N,\N,"Action,Adventure,Sci-Fi",NaN,NaN

In [120]:
print('Após amostra aleatória de 3 filmes com data de lançamento futura, identificamos que os dados estão corretos, indicando que esses filmes realmente possuem data de lançamento futura.')
print('Esses filmes serão desconsiderados.')

Após amostra aleatória de 3 filmes com data de lançamento futura, identificamos que os dados estão corretos, indicando que esses filmes realmente possuem data de lançamento futura.
Esses filmes serão desconsiderados.

In [122]:
df_filmes_brasileiros.drop(df_filmes_brasileiros[df_filmes_brasileiros['startYear'] > 2026].index, inplace=True)

In [123]:
df_filmes_brasileiros[df_filmes_brasileiros['startYear'] > 2026]

Empty DataFrame
Columns: [titleId, ordering, title, region, language, types, attributes, isOriginalTitle, titleType, primaryTitle, originalTitle, isAdult, startYear, endYear, runtimeMinutes, genres, averageRating, numVotes]
Index: []

In [131]:
df_filmes_brasileiros['startYear'] = df_filmes_brasileiros['startYear'].replace(0,None)

In [133]:
print('Nesta análise, o período de tempo considerado para os filmes brasileiros é de {} a {}, abrangendo um total de {} anos.'.format(df_filmes_brasileiros['startYear'].min(), df_filmes_brasileiros['startYear'].max(), df_filmes_brasileiros['startYear'].max() - df_filmes_brasileiros['startYear'].min()))

Nesta análise, o período de tempo considerado para os filmes brasileiros é de 1903 a 2026, abrangendo um total de 123 anos.