In [1]:
import pandas as pd

<h1>Exploração de dados inicial.</h1>
<h2>Nessa etapa, busca-se realizar uma exploração de dados</h2>

carregando os datasets ao notebooks

In [6]:
df_titles = pd.read_csv(r'..\datasets\title.akas.tsv', sep='\t')
df_titles_basic = pd.read_csv(r'..\datasets\title.basics.tsv', sep='\t')
df_titles_episode = pd.read_csv(r'..\datasets\title.episode.tsv', sep='\t')
df_titles_principals = pd.read_csv(r'..\datasets\title.principals.tsv', sep='\t')
df_titles_ratings = pd.read_csv(r'..\datasets\title.ratings.tsv', sep='\t')

informações dos respectivos dataframes

In [27]:

df_titles.info()
df_titles.head()

<class 'pandas.DataFrame'>
RangeIndex: 55754007 entries, 0 to 55754006
Data columns (total 8 columns):
 #   Column           Dtype
---  ------           -----
 0   titleId          str
 1   ordering         int64
 2   title            str
 3   region           str
 4   language         str
 5   types            str
 6   attributes       str
 7   isOriginalTitle  int64
dtypes: int64(2), str(6)
memory usage: 3.3 GB

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Carmencita,\N,\N,original,\N,1
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita,US,\N,imdbDisplay,\N,0
3,tt0000001,4,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
4,tt0000001,5,Καρμενσίτα,GR,\N,imdbDisplay,\N,0

In [20]:
df_titles_basic.info()
df_titles.head()

<class 'pandas.DataFrame'>
RangeIndex: 12420966 entries, 0 to 12420965
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          str
 1   titleType       str
 2   primaryTitle    str
 3   originalTitle   str
 4   isAdult         int64
 5   startYear       str
 6   endYear         str
 7   runtimeMinutes  str
 8   genres          str
dtypes: int64(1), str(8)
memory usage: 852.9 MB

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Carmencita,\N,\N,original,\N,1
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita,US,\N,imdbDisplay,\N,0
3,tt0000001,4,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
4,tt0000001,5,Καρμενσίτα,GR,\N,imdbDisplay,\N,0

In [23]:
df_titles_episode.info()
df_titles_episode.head()

<class 'pandas.DataFrame'>
RangeIndex: 9591630 entries, 0 to 9591629
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   tconst         str
 1   parentTconst   str
 2   seasonNumber   str
 3   episodeNumber  str
dtypes: str(4)
memory usage: 292.7 MB

      tconst parentTconst seasonNumber episodeNumber
0  tt0031458   tt32857063           \N            \N
1  tt0041951    tt0041038            1             9
2  tt0042816    tt0989125            1            17
3  tt0042889    tt0989125           \N            \N
4  tt0043426    tt0040051            3            42

In [24]:
df_titles_principals.info()
df_titles_principals.head()

<class 'pandas.DataFrame'>
RangeIndex: 2655458 entries, 0 to 2655457
Data columns (total 6 columns):
 #   Column      Dtype
---  ------      -----
 0   tconst      str
 1   ordering    float64
 2   nconst      str
 3   category    str
 4   job         str
 5   characters  str
dtypes: float64(1), str(5)
memory usage: 121.6 MB

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1.0,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2.0,nm0005690,director,\N,\N
2,tt0000001,3.0,nm0005690,producer,producer,\N
3,tt0000001,4.0,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1.0,nm0721526,director,\N,\N

In [26]:
df_titles_ratings.info()
df_titles_ratings.head()

<class 'pandas.DataFrame'>
RangeIndex: 1658155 entries, 0 to 1658154
Data columns (total 3 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   tconst         1658155 non-null  str
 1   averageRating  1658155 non-null  float64
 2   numVotes       1658155 non-null  int64
dtypes: float64(1), int64(1), str(1)
memory usage: 38.0 MB

      tconst  averageRating  numVotes
0  tt0000001            5.7      2201
1  tt0000002            5.5       312
2  tt0000003            6.4      2314
3  tt0000004            5.1       197
4  tt0000005            6.2      3039